import sharp from "sharp";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

export const LOGO_PATH = join(process.cwd(), "public", "logo admin.png");
export const WATERMARK_OPACITY = 0.65;
export const ORIGINALS_PREFIX = "originals";

// Filenames generated by the admin upload route look like
// "1751812345678-a1b2c3d4e.webp" (Date.now() + random suffix). Any filename
// that does NOT match this pattern came from the legacy site
// import/migration and must never be (re)watermarked by the system.
export const ADMIN_UPLOAD_FILENAME_RE = /^\d{10,}-[a-z0-9]+\.webp$/i;

export function isAdminUploadFilename(filename: string): boolean {
  return ADMIN_UPLOAD_FILENAME_RE.test(filename);
}

export async function applyWatermark(
  fileBuffer: Buffer,
  outWidth: number,
  outHeight: number,
  quality: number
): Promise<Buffer> {
  const image = sharp(fileBuffer).resize(outWidth, outHeight, {
    fit: "cover",
    position: "center",
  });

  if (!existsSync(LOGO_PATH)) {
    return image.webp({ quality }).toBuffer();
  }

  const logoWidth = Math.round(outWidth * 0.42);
  const resizedBuffer = await sharp(readFileSync(LOGO_PATH))
    .resize(logoWidth)
    .ensureAlpha()
    .toBuffer();

  const { data, info } = await sharp(resizedBuffer)
    .raw()
    .toBuffer({ resolveWithObject: true });

  for (let i = 3; i < data.length; i += 4) {
    data[i] = Math.round(data[i] * WATERMARK_OPACITY);
  }

  const logoFinal = await sharp(Buffer.from(data), {
    raw: { width: info.width, height: info.height, channels: 4 },
  })
    .png()
    .toBuffer();

  const left = Math.round((outWidth - logoWidth) / 2);
  const top = Math.round(outHeight * 0.8 - info.height / 2);

  return image
    .composite([{ input: logoFinal, left, top, blend: "over" }])
    .webp({ quality })
    .toBuffer();
}
